---
abstract: 'Hannover Perl Mongers'
author:
  - 'Paul Cochrane <ptc@hannover.pm>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: PerlMongers-Hannover
requires:
  Capture::Tiny: '0'
  Test::More: '0'
  perl: v5.10.1
version: '0.03'
